### PR TITLE
Added my details

### PR DESCRIPTION
**Pull request by nmcl**
Transactional Vert.x (STM)

### CODE REVIEW

**Comment by michel-kraemer** [comment]
I'm sorry, but I need to validate all requests before I can merge them. Would you mind giving me a link to a commit that was successfully merged into one of the official Vert.x repositories? Or the link to your project contributing to the Vert.x ecosystem? Thank you so much!

By the way, I just changed the community page. The contributors are now in a JSON array and the HTML code is automatically generated in the template. This way we can make sure all entries look the same. I can try to update your pull request, but if you like you can also do it yourself.

Thanks,
Michel

**Comment by nmcl** [comment]
No worries. Tim knows this is request is coming so feel free to ping him too. But this is the repo (Vert.x 2).

https://github.com/nmcl/TransactionalVert.x

**Comment by purplefox** [comment]
Normally we would only count someone as a contributor if they have something committed in one of the official Vert.x repos, but as Mark has been an important figure in helping the Vert.x community get to where it is, I'm going to make an exception here, and add his details manually.

**Comment by purplefox** [comment]
Closing this, as I will add it manually.

**Pull request closed without merging**
