### PR TITLE
Responsive footer

### PR DESCRIPTION
**Pull request by santo74**
I made the footer more responsive.
Feel free to merge it in case you like it.

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Looks great. Thanks! I will test it in my fork later today.

**Comment by michel-kraemer** [comment]
Tested it on my fork. Looks good. Can be merged from my point of view.

**Comment by santo74** [comment]
Is there something else that needs to be done in order to have this pull request merged into master?

**Comment by michel-kraemer** [comment]
Please rebase. Many things have changed since you submitted the request and it cannot be merged at the moment.

**Comment by michel-kraemer** [comment]
Thanks for the contribution. I tried to mimic your changes in 8701052 and closed this issue.

**Comment by santo74** [comment]
Great! Thanks for taking the time to integrate my changes.

**Pull request closed without merging**
