### PR TITLE
Redesign manual pages

### LINKED ISSUE #10: Redesign manual pages
They should have the same design as the main website.

The table of contents should be sticky anyhow. Maybe like they did it on the bootstrap site:
http://getbootstrap.com/css/

... but with a larger font size.

### LINKED ISSUE #11: Minify javascript
Uglify.js, Google Closure Compiler or YUI Compressor. Does anybody know how to do this with Maven/JBake?

### LINKED ISSUE #12: Minify CSS
Even though we use SASS the bootstrap CSS can become really large! Does anybody know how to do this with Maven/JBake?

### PR DESCRIPTION
**Pull request by michel-kraemer**
All manual pages are now fully integrated in the main website's design.

Closes #10 

* Also closes #12 because Gulp is used now to minify generated CSS.
* Also closes #11 because bower is used now to get the dependencies and the minified version of bootstrap is used.
* frontend-maven-plugin is used to execute Gulp from Maven. Tested under Windows and Linux. Should run under Mac as well.
* Changes can be previewed here: http://vert-x3-preview.michel-kraemer.com/docs.html

Sorry for this rather large PR, but it's been quite some work.

### CODE REVIEW

**Comment by purplefox** [comment]
Hi Michel, 

this looks good but seems to be out of sync with master. Could you perhaps rebase it?

Thanks.

**Comment by michel-kraemer** [comment]
Yes I know. This is due to Julien's changes. It's not working properly anyhow (see my message on the mailing list). I'll send another PR to get rid of JBake first and then update this one.

**Comment by purplefox** [comment]
Ok, will merge this once it's updated :)

**Comment by michel-kraemer** [comment]
Ready to be merged now.

**Comment by purplefox** [comment]
Michel-

One thing I noticed with this is that some of the links, e.g. to /javascripts/*, /assets/* etc now use absolute links not relative links so the site does not render any more when opened as a file in a browser (which is what I do to preview it).

**Comment by purplefox** [comment]
I think relative links are preferable - then it's much easier to move the site to a different root in the future (e.g. when we go live we will run the Vert.x 2 and Vert.x 3 sites in parallel on the same domain, as we still have many Vert.x 2 users, and perhaps the Vert.x 2 root is at http://vertx.io/vertx2 and http://vertx.io/vertx3)

**Comment by michel-kraemer** [comment]
Thanks a lot for merging so quickly.

I see your point. I also prefer relative links, but there's an issue with the links in the site header and footer for the docs pages. For example, compare `docs/vertx-unit/java/index.html` with `index.html`. The correct relative links to the main documentation page, for example, are `../../../docs.html` and `docs.html` respectively. We need a way to generate relative links dynamically depending on where in the directory structure the header and footer templates are included.

Since all docs use the same directory structure we could probably just add a simple if statement to all links:

    {% if layout == 'docs.html' %}../../../{% endif %}docs.html

But this would bloat the code and IMHO also make it hard to maintain. I suppose there will be more pages in the future and we may need to add more if statements, etc.

I've been working on a couple of websites and my strategy to solve this was always as follows:
* Define a global variable `site_url` pointing to the root of your website (e.g. `http://vertx.io/` or `http://vertx.io/vert-x3/` or even `file:///.....`)
* Add `site_url` to all relative links like this: `<a href="{{ site_url }}docs.html">`
* Run a small web server to preview the site. You can do this with `gulp watch` and then going to `http://localhost:4000`.

As I said, this strategy has been proven to work really well in many previous projects. It is scalable and maintainable. It also supports moving the site, because all you need to do is update the global `site_url` variable.

By the way, this strategy is also recommended by jekyll. They use a `baseurl` configuration variable for this.

What do you think?

Cheers,
Michel

**Comment by purplefox** [comment]
Seems like a good approach

**Comment by michel-kraemer** [comment]
OK. Another PR is about to come. Give me a couple of days. I'm currently super-busy. But Sunday should be OK.

**Pull request merged**
