### PR TITLE
Added contributor Marcel Soute

### PR DESCRIPTION
**Pull request by msoute**

### CODE REVIEW

**Comment by michel-kraemer** [comment]
I'm sorry, but I need to validate all requests before I can merge them. Would you mind giving me a link to a commit that was successfully merged into one of the official Vert.x repositories? Or the link to your project contributing to the Vert.x ecosystem? Thank you so much!

By the way, I just changed the community page. The contributors are now in a JSON array and the HTML code is automatically generated in the template. This way we can make sure all entries look the same. I can try to update your pull request, but if you like you can also do it yourself.

Thanks,
Michel

**Comment by msoute** [comment]
https://github.com/eclipse/vert.x/pulls/msoute

**Comment by msoute** [comment]
@michel-kraemer added info in JSON array

**Comment by michel-kraemer** [comment]
Great! Thanks!

**Pull request merged**
