### PR TITLE
Adding contributor.

### PR DESCRIPTION
**Pull request by garnold**

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the PR! I'm really sorry, but I need to validate all requests before I can merge them. Would you mind giving me a link to a commit that was successfully merged into one of the official Vert.x repositories? Or the link to your project contributing to the Vert.x ecosystem? Thank you so much!

Thanks,
Michel

**Comment by garnold** [comment]
Hey @michel-kraemer , no problem!

Turns out that my pulls sat out there untouched for so long that master was swapped out from underneath (they also appear to have been haphazardly rebased):

https://github.com/eclipse/vert.x/pull/823
https://github.com/eclipse/vert.x/pull/824

I'm happy to do the work to rebase and resubmit, but it'd be great if you guys could take a look sooner than later (something less that two months this time :wink:)

Let me know.

**Comment by michel-kraemer** [comment]
You should post this on the vertx-dev mailing list, so Tim or Julien can have a look.

**Comment by garnold** [comment]
@michel-kraemer Ah, I originally posted the pulls to vertx@googlegroups.com:

https://groups.google.com/d/msg/vertx/iG374ZzLJPo/QaYopewzGeMJ

Maybe that's why they were lost.  So you would recommend recreating the pulls?

**Comment by michel-kraemer** [comment]
I'm not really sure. Only Tim or Julien can decide this. I was just suggesting that discussing your issue on the vertx-dev mailing list would be better than here.

**Comment by kuujo** [comment]
I wouldn't waste your time cleaning up those PRs. There's way too much going on on the 3.x stuff, so They won't go anywhere now, but perhaps they will still credit you with your contribution.

**Comment by garnold** [comment]
Thanks @kuujo and @michel-kraemer!  I guess I'll just wait to see what @purplefox @vietj have to say.

**Comment by purplefox** [comment]
It's turning out too much hassle to manually add each contributor so now we're taking the approach of auto-generating the list from the GitHub API, so if you've made contributions you will automatically appear :)

**Pull request closed without merging**
